apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -o kompose-manifest convert
    kompose.version: 1.2.0 (99f88ef)
  creationTimestamp: null
  labels:
    io.kompose.service: front-end
  name: front-end
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: front-end
    spec:
      containers:
      - image: weaveworksdemos/front-end
        name: front-end
        resources: {}
        securityContext:
          capabilities:
            drop:
            - all
      restartPolicy: Always
status: {}
