kind: PersistentVolume
apiVersion: v1
metadata:
  name: queue-master-persistentvolume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/run/docker.sock"
